[build]
  command = "npm run build:production"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NEXT_DISABLE_ESLINT = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_EXPERIMENTAL_SSR = "1"
  NEXT_DISABLE_STATIC_EXPORT = "false"
  NEXT_SKIP_TYPE_CHECK = "true"

# Skip Python installation since we're using a JavaScript-only approach
[build.processing.skip]
  pip = true 