[build]
  command = "node scripts/netlify-build.js"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "1"
  NODE_VERSION = "18"
  NEXT_DISABLE_ESLINT = "1"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SKIP_TYPE_CHECK = "1"
  DISABLE_ESLINT_PLUGIN = "true"

# Skip Python installation since we're using a JavaScript-only approach
[build.processing.skip]
  pip = true 