[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_DISABLE_ESLINT = "1"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SKIP_TYPE_CHECK = "1"
  DISABLE_ESLINT_PLUGIN = "true"
  ESLINT_NO_DEV_ERRORS = "true"
  SKIP_ESLINT_CHECK = "true"

# Skip Python installation since we're using a JavaScript-only approach
[build.processing.skip]
  pip = true

# Disable all plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"
  enabled = false 