[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_DISABLE_ESLINT = "1"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SKIP_TYPE_CHECK = "1"
  DISABLE_ESLINT_PLUGIN = "1"
  ESLINT_NO_DEV_ERRORS = "1"
  SKIP_ESLINT_CHECK = "1"
  NEXT_MINIMAL = "1"
  NEXT_PRIVATE_SKIP_TYPE_CHECK = "1"
  NEXT_PRIVATE_SKIP_VALIDATION = "1"

# Skip Python installation since we're using a JavaScript-only approach
[build.processing.skip]
  pip = true

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    functions = "netlify/functions"
    publish = ".next"

# No plugins needed for this build 