[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

# Skip Python installation since we're using a JavaScript-only approach
[build.processing.skip]
  pip = true 